- alias: Fan 1 Notification
  trigger:
    platform: mqtt
    topic: "stat/fan1/POWER"
    # Optional
    payload: "ON"
  action:
    service: notify.gmail
    data:
      message: "Fan 1 turned on"
      title: "Fan 1 Notification"

- alias: Basement Cabinet Right Notification
  trigger:
    platform: state
    entity_id: binary_sensor.basement_cabinet_sensor_right_sensor_6_0
    # Optional
    #state: on
    from: 'off'
    to: 'on'
  action:
    - service: script.foscam_basement1_record
    - delay: 00:00:60
    - service: notify.gmail
      data:
        message: "Basement Cabinet Right Opened"
        title: "Home Assistant Notification"
        data:
          images:
            - /home/pi/Videos/cam01/latest.mp4

- alias: Basement Cabinet Left Notification
  trigger:
    platform: state
    entity_id: binary_sensor.basement_cabinet_sensor_left_sensor_5_0
    # Optional
    #state: on
    from: 'off'
    to: 'on'
  action:
    - service: script.foscam_basement1_record
    - delay: 00:00:60
    - service: notify.gmail
      data:
        message: "Basement Cabinet Left Opened"
        title: "Home Assistant Notification"
        data:
          images:
            - /home/pi/Videos/cam01/latest.mp4

- alias: 'Battery Low Alert - Kitchen Sink Water Sensor'
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_sink_water_sensor_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Kitchen Sink Water Sensor"
      title: "Home Assistant Notification"

- alias: 'Battery Low Alert - Basement Floor Sump Water Sensor'
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_floor_sump_water_sensor_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Basement Floor Sump Water Sensor"
      title: "Home Assistant Notification"

- alias: 'Battery Low Alert - Laundry Water Sensor'
  trigger:
    platform: numeric_state
    entity_id: sensor.laundry_water_sensor_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Laundry Water Sensor"
      title: "Home Assistant Notification"

- alias: 'Battery Low Alert - Basement Cabinet Sensor Left'
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_cabinet_sensor_left_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Basement Cabinet Sensor Left"
      title: "Home Assistant Notification"

- alias: 'Battery Low Alert - Basement Cabinet Sensor Right'
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_cabinet_sensor_right_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Basement Cabinet Sensor Right"
      title: "Home Assistant Notification"

- alias: 'Battery Low Alert - Siren 1'
  trigger:
    platform: numeric_state
    entity_id: sensor.siren_1_battery
    below: 90
  action:
    service: notify.gmail
    data:
      message: "Battery Low Alert - Siren 1"
      title: "Home Assistant Notification"
