- alias: Fan 1 Notification
  trigger:
    platform: mqtt
    topic: "stat/fan1/POWER"
    # Optional
    payload: "ON"
  action:
    service: notify.gmail
    data:
      message: "Fan 1 turned on"
      title: "Fan 1 Notification"


- alias: Basement Cabinet Right Notification
  trigger:
    platform: state
    entity_id: binary_sensor.basement_cabinet_sensor_right_sensor_6_0
    # Optional
    #state: on
    from: 'off'
    to: 'on'
  action:
    service: notify.gmail
    data:
      message: "Basement Cabinet Right Opened"
      title: "Home Assistant Notification"

- alias: Basement Cabinet Left Notification
  trigger:
    platform: state
    entity_id: binary_sensor.basement_cabinet_sensor_left_sensor_5_0
    # Optional
    #state: on
    from: 'off'
    to: 'on'
  action:
    service: notify.gmail
    data:
      message: "Basement Cabinet Left Opened"
      title: "Home Assistant Notification"
