homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.574934
  longitude: -93.766389
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 292
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    group.all_automations:
      hidden: false
    group.all_devices:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_locks:
      hidden: false
    group.all_remotes:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_switches:
      hidden: false


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr

  - platform: template
    sensors:
      kitchen_sink_water_sensor_battery:
        value_template: >-
          {%- if states.zwave.kitchen_sink_water_sensor -%}
            {{ states.zwave.kitchen_sink_water_sensor.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.kitchen_sink_water_sensor

  - platform: template
    sensors:
      basement_floor_sump_water_sensor_battery:
        value_template: >-
          {%- if states.zwave.basement_floor_sump_water_sensor -%}
            {{ states.zwave.basement_floor_sump_water_sensor.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.basement_floor_sump_water_sensor

  - platform: template
    sensors:
      laundry_water_sensor_battery:
        value_template: >-
          {%- if states.zwave.laundry_water_sensor -%}
            {{ states.zwave.laundry_water_sensor.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.laundry_water_sensor

  - platform: template
    sensors:
      basement_cabinet_sensor_left_battery:
        value_template: >-
          {%- if states.zwave.basement_cabinet_sensor_left -%}
            {{ states.zwave.basement_cabinet_sensor_left.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.basement_cabinet_sensor_left

  - platform: template
    sensors:
      basement_cabinet_sensor_right_battery:
        value_template: >-
          {%- if states.zwave.basement_cabinet_sensor_right -%}
            {{ states.zwave.basement_cabinet_sensor_right.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.basement_cabinet_sensor_right

  - platform: template
    sensors:
      siren_1_battery:
        value_template: >-
          {%- if states.zwave.siren_1 -%}
            {{ states.zwave.siren_1.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.siren_1

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use

binary_sensor:
  - platform: template
    sensors:
      kitchen_to_garage_door:
        value_template: "{{ states.sensor.kitchen_to_garage_door_sensor_access_control.state == '22' }}"
        friendly_name: 'Kitchen to Garage Door'
        device_class: "opening"
        entity_id: sensor.kitchen_to_garage_door_sensor_access_control

sensor 1:
  - platform: mqtt
    name: "Porch Temperature"
    state_topic: "/haenvporch/env/temperature"
    qos: 0
    unit_of_measurement: "F"

sensor 2:
  - platform: mqtt
    name: "Porch Humidity"
    state_topic: "/haenvporch/env/humidity"
    qos: 0
    unit_of_measurement: "%"

sensor 3:
  - platform: mqtt
    name: "Porch Env Battery"
    state_topic: "/haenvporch/battery/level"
    qos: 0
    unit_of_measurement: "%"

binary_sensor 1:
  - platform: mqtt
    name: "Garage Door Overhead"
    state_topic: "/hadoorgarovhd/door/open"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: "opening"

# Text to speech
tts:
  platform: google

recorder: !include recorder.yaml

notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: brooke.hedrick.family@gmail.com
    starttls: true
    username: !secret gmail_family_username
    password: !secret gmail_family_password
    recipient:
      - brooke.t.hedrick@gmail.com
    sender_name: My Home Assistant

group: !include groups.yaml
automation: !include automations.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

switch:
  - platform: mqtt
    name: "Drew Fan"
    command_topic: "cmnd/fan1/POWER"
    state_topic: "stat/fan1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "fan2"
    command_topic: "cmnd/fan2/power"
    state_topic: "stat/fan2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true


# Example configuration.yaml entry
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  device_config:
    switch.garage_can_lights_switch:
      polling_intensity: 1
    switch.house_front_door_and_garage_lights_switch:
      polling_intensity: 1
    switch.living_room_lights_switch:
      polling_intensity: 1
    light.dining_room_lights_level:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.basement_lights_level:
      polling_intensity: 1
      refresh_value: true
      delay: 3
#  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config

camera:
  - platform: foscam
    ip: 192.168.0.195
    name: cam_basement1
    port: 88
    username: !secret camera_foscam_basement1_username
    password: !secret camera_foscam_basement1_password

camera 2:
  - platform: ffmpeg
    name: cap_basement1
    input: /home/pi/Videos/cam01/latest.mp4

shell_command:
  foscam_basement1_record: '/home/homeassistant/.homeassistant/scripts/cam_record_basement1.sh'


script:
  foscam_basement1_record:
    sequence:
    - service: shell_command.foscam_basement1_record

# https://home-assistant.io/components/cloud.alexa/
cloud:
  alexa:
    filter:
      include_entities:
        - switch.garage_can_lights_switch
        - switch.house_front_door_and_garage_lights_switch
        - switch.drew_fan
        - switch.living_room_lights_switch
        - light.basement_lights_level
        - light.dining_room_lights_level
#      include_domains:
#        - switch
#        - light
#      exclude_entities:
#        - switch.outside
#        - switch.siren_1_switch
#        - switch.fan2
#        - switch.aeotec_zw056_doorbell_gen5_switch
    entity_config:
      light.kitchen:
        name: Custom Name for Alexa
        description: The light in the kitchen
      switch.garage_can_lights_switch:
        name: Garage lights
        description: The can lights in the garage
        display_categories: LIGHT
      switch.house_front_door_and_garage_lights_switch:
        name: Front lights
        description: The front door lights
        display_categories: LIGHT
      switch.drew_fan:
        name: Drew's fan
        description: Fan in Drew's bedroom
      switch.living_room_lights_switch:
        name: Living Room lights
        description: The lights in the living room
        display_categories: LIGHT
      light.basement_lights_level:
        name: Basement lights
        description: The lights in the basement
        display_categories: LIGHT
      light.dining_room_lights_level:
        name: Dining Room Lights
        description: The lights in the dining room
        display_categories: LIGHT

